use_frameworks!


source 'https://e.coding.net/hongyiapp/hongyizujian/PrivatePod.git'
#source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'QRCodeScan_Example' do
  pod 'QRCodeScan', :path => '../'
  pod 'Utils'
  target 'QRCodeScan_Tests' do
    inherit! :search_paths

    
  end
end
